name: linting, testing, building
run-name: ${{ github.actor }} linting, testing, building 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build project prod
        run: npm run build:prod
      - name: lint typescript
        run: npm run lint:ts
        if: always()
      - name: lint css
        run: npm run lint:scss
        if: always()
      - name: unit
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: test:storybook
        run: npm run test:ui:ci
        if: always()
